//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tataiee.Harif.WpfApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public char Gender {
            get {
                return ((char)(this["Gender"]));
            }
            set {
                this["Gender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CurrentTermNumber {
            get {
                return ((int)(this["CurrentTermNumber"]));
            }
            set {
                this["CurrentTermNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MinUnits {
            get {
                return ((int)(this["MinUnits"]));
            }
            set {
                this["MinUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int MaxUnits {
            get {
                return ((int)(this["MaxUnits"]));
            }
            set {
                this["MaxUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TimeoutForReductionStep2ms {
            get {
                return ((int)(this["TimeoutForReductionStep2ms"]));
            }
            set {
                this["TimeoutForReductionStep2ms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CapacityFiltering {
            get {
                return ((bool)(this["CapacityFiltering"]));
            }
            set {
                this["CapacityFiltering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExamCollideChecking {
            get {
                return ((bool)(this["ExamCollideChecking"]));
            }
            set {
                this["ExamCollideChecking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int WeeklyProgram_StartHour {
            get {
                return ((int)(this["WeeklyProgram_StartHour"]));
            }
            set {
                this["WeeklyProgram_StartHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int WeeklyProgram_Length {
            get {
                return ((int)(this["WeeklyProgram_Length"]));
            }
            set {
                this["WeeklyProgram_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1")]
        public double WeeklyProgram_MinuteWidth {
            get {
                return ((double)(this["WeeklyProgram_MinuteWidth"]));
            }
            set {
                this["WeeklyProgram_MinuteWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double WeeklyProgram_BorderThickness {
            get {
                return ((double)(this["WeeklyProgram_BorderThickness"]));
            }
            set {
                this["WeeklyProgram_BorderThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double WeeklyProgram_Padding {
            get {
                return ((double)(this["WeeklyProgram_Padding"]));
            }
            set {
                this["WeeklyProgram_Padding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public double WeeklyProgram_FontSize {
            get {
                return ((double)(this["WeeklyProgram_FontSize"]));
            }
            set {
                this["WeeklyProgram_FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public double WeeklyProgram_MinHeight {
            get {
                return ((double)(this["WeeklyProgram_MinHeight"]));
            }
            set {
                this["WeeklyProgram_MinHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double WeeklyProgram_DataGridCourseInfoWidth {
            get {
                return ((double)(this["WeeklyProgram_DataGridCourseInfoWidth"]));
            }
            set {
                this["WeeklyProgram_DataGridCourseInfoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\\\Reports\\\\AlgorithmReports\\\\SavedAlgorithmExeOutputs\\\\")]
        public string WeeklyProgramSavedDirectory {
            get {
                return ((string)(this["WeeklyProgramSavedDirectory"]));
            }
            set {
                this["WeeklyProgramSavedDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int AlgorithmMaxProcessingTimeMS {
            get {
                return ((int)(this["AlgorithmMaxProcessingTimeMS"]));
            }
            set {
                this["AlgorithmMaxProcessingTimeMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReductionStep2MustBeLoad {
            get {
                return ((bool)(this["ReductionStep2MustBeLoad"]));
            }
            set {
                this["ReductionStep2MustBeLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HomePageVisibility {
            get {
                return ((bool)(this["HomePageVisibility"]));
            }
            set {
                this["HomePageVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreditDeterminerVisibility {
            get {
                return ((bool)(this["CreditDeterminerVisibility"]));
            }
            set {
                this["CreditDeterminerVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AdaptTableVisibility {
            get {
                return ((bool)(this["AdaptTableVisibility"]));
            }
            set {
                this["AdaptTableVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StudHistoryVisibility {
            get {
                return ((bool)(this["StudHistoryVisibility"]));
            }
            set {
                this["StudHistoryVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OfferedCourseManagerVisibility {
            get {
                return ((bool)(this["OfferedCourseManagerVisibility"]));
            }
            set {
                this["OfferedCourseManagerVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReductionStep2SettingVisibility {
            get {
                return ((bool)(this["ReductionStep2SettingVisibility"]));
            }
            set {
                this["ReductionStep2SettingVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartPage {
            get {
                return ((int)(this["StartPage"]));
            }
            set {
                this["StartPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AlgorithmAnimationEffectStatus {
            get {
                return ((int)(this["AlgorithmAnimationEffectStatus"]));
            }
            set {
                this["AlgorithmAnimationEffectStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int MaxNumberOfSuggestedWeeklyProgram {
            get {
                return ((int)(this["MaxNumberOfSuggestedWeeklyProgram"]));
            }
            set {
                this["MaxNumberOfSuggestedWeeklyProgram"] = value;
            }
        }
    }
}
